version: "3.9"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  ofdata-reader:
    build:
      context: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src/:/src/
      - ./db/:/db/
      - ./configs/:/configs/
    entrypoint:
      - python
      - project/main.py
      # - --dbname=einebiene.sqlite  # An example on how to pass CL arguments.
