version: "3.9"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  ofdata-reader:
    build:
      context: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src/:/src/
      - ./db/:/db/
      - ./configs/:/configs/
    depends_on:
      - sqlite3
    entrypoint:
      - python
      - project/main.py
#      - --file=egrul.json.zip  # An example on how to pass CLI arguments.
#      - -n=1000
#      - --dbname=einebiene.sqlite
